version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
      - ./:/app
      - /app/node_modules
      # PÅ™idÃ¡me toto, aby se sloÅ¾ka .next nepropisovala z Windows do Linuxu a nedÄ›lala bordel
      - /app/.next 
    environment:
      - DATABASE_URL=file:./dev.db
    # ğŸ‘‡ TOTO JE TA ZMÄšNA - SpustÃ­me vÃ½vojÃ¡Å™skÃ½ mÃ³d mÃ­sto produkÄnÃ­ho
    command: npm run dev